version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    open-pull-requests-limit: 20
    groups:
      Svelte:
        patterns:
          - "svelte"
          - "svelte-check"
          - "@sveltejs/*"
      linter:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "prettier*"
      UI:
        patterns:
          - "melt"
          - "@melt-ui/*"
          - "@floating-ui/dom"
          - "@tabler/*"
      rx-nostr:
        patterns:
          - "rx-nostr"
          - "rx-nostr-crypto"
          - "rxjs"
          - "nostr-typedef"
      TypeScript:
        patterns:
          - "tslib"
          - "typescript"
      async-lock:
        patterns:
          - "async-lock"
          - "@types/async-lock"
      qrcode:
        patterns:
          - "qrcode"
          - "@types/qrcode"
      twitter-text:
        patterns:
          - "twitter-text"
          - "@types/twitter-text"
      gdpr-cookie-consent-banner:
        patterns:
          - "@beyonk/gdpr-cookie-consent-banner"
          - "@types/beyonk__gdpr-cookie-consent-banner"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    cooldown:
      default-days: 14
    groups:
      all:
        applies-to: version-updates
        patterns:
          - "*"
