name: Dependabot workaround
description: Workaround for npm ci error

on:
  pull_request:
    paths:
      - web/package.json

permissions:
  contents: write

jobs:
  rerun-npm-install:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install
      - id: diff
        run: git diff --name-only --exit-code web/package-lock.json
        continue-on-error: true
      - uses: snow-actions/git-config-user@v1.0.0
        if: steps.diff.outcome == 'failure'
      - run: |
          git add web/package-lock.json
          git commit -m "npm install"
          git push
        if: steps.diff.outcome == 'failure'
      
    
