name: Stats

on:
  push:
    branches:
      - main

jobs:
  stats:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6.3.0
        with:
          node-version: "24.x"
      - run: npm ci
      - run: cp .env.example .env
      - run: npm run build
      - run: |
          echo "# Bundle Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Client" >> $GITHUB_STEP_SUMMARY
          sed -n "2,10p" .svelte-kit/output/client/stats.md >> $GITHUB_STEP_SUMMARY
          echo "## Server" >> $GITHUB_STEP_SUMMARY
          sed -n "2,10p" .svelte-kit/output/server/stats.md >> $GITHUB_STEP_SUMMARY

          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "<summary>Client Details</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat .svelte-kit/output/client/stats.md >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY

          echo "<details>" >> $GITHUB_STEP_SUMMARY
          echo "<summary>Server Details</summary>" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          cat .svelte-kit/output/server/stats.md >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "</details>" >> $GITHUB_STEP_SUMMARY
