/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 17bc807eafaef43bcc40400ad23cd953)
interface __BaseEnv_Env {
	RESTRICTION: KVNamespace;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
